apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkinss
    image: jenkins
    ports:
     - containerPort: 8080
     - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  - port: 50000
    protocol: TCP
    name: agent-port
  selector:
    app: jenkins
