apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 80
    volumeMounts:
    - name: photon-storage
      mountPath: /data
  volumes:
  - name: photon-storage
    persistentVolumeClaim:
      claimName: demo-claim
