apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-k8s
  labels:
    app: grafana-k8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: grafana-k8s
    spec:
      containers:
        - name: grafana-k8s
          image: grafana/grafana
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    run: grafana-k8s
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    run: grafana-k8s

